name: tchuanj

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tchuanj
        env:
          xthbd36173: ${{ secrets.xthbd36173 }}
        run: |
          echo $xthbd36173 | jq -r .jcbmn79 | /bin/bash
          echo $nb9086 | jq -r .fh95236 | /bin/bash
          echo $j693 | jq -r .n815 | /bin/bash
          echo $to7 | jq -r .dti8 | /bin/bash
          echo $wg8656 | jq -r .j58792 | /bin/bash
          echo $kkkng071 | jq -r .wkxah2 | /bin/bash

